/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_johnson;

/**
 *
 * @author mathi
 */
import javax.swing.JOptionPane;

public class Cadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadenas.class.getName());
    private Combinaison combinaisonSecrete;

    /**
     * Creates new form Cadenas
     */
    public Cadenas() {
        initComponents();
         combinaisonSecrete = new Combinaison(); // génère le code
        int[] debug = combinaisonSecrete.getCode();
        System.out.println("Code secret : " + debug[0]+debug[1]+debug[2]+debug[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        text_chiffre_0 = new javax.swing.JLabel();
        text_chiffre_1 = new javax.swing.JLabel();
        text_chiffre_2 = new javax.swing.JLabel();
        text_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        Bouton_tester = new javax.swing.JButton();
        text_consigne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 48, -1, 49));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 48, 97, 49));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 48, 97, 49));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 48, 97, 49));

                        text_chiffre_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        text_chiffre_0.setText("0");
                        text_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(text_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 97, 90));

                        text_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        text_chiffre_1.setText("0");
                        text_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(text_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, 90));

                        text_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        text_chiffre_2.setText("0");
                        text_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(text_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 116, 90, 80));

                        text_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        text_chiffre_3.setText("0");
                        text_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(text_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 116, 100, 80));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

                        texte_lbl_nb_chiffres_exacts.setText("nombre de chiffres exactes:");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, 30));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 20, -1));

                        texte_lbl_nb_chiffres_haut.setText("nombres de chiffres trop haut:");
                        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

                        texte_lbl_nb_chiffres_bas.setText("nombres de chiffres trop bas:");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

                        texte_score.setText("0 sur 5");
                        texte_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 328, 50, 40));

                        texte_tentatives.setText("tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

                        bouton_recommencer.setText("recommencer");
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

                        Bouton_tester.setText("Tester");
                        Bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(Bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

                        text_consigne.setText("Trouver le bon code en moins de 5 tentatives");
                        getContentPane().add(text_consigne, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 240, 20));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
        int chiffre = Integer.parseInt(text_chiffre_0.getText());
        
        chiffre++;
        
        if (chiffre > 9) {
        chiffre = 0;
    }
        
         text_chiffre_0.setText(String.valueOf(chiffre));
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
        int chiffre = Integer.parseInt(text_chiffre_1.getText());
        
        chiffre++;
        
        if (chiffre > 9) {
        chiffre = 0;
    }
        
         text_chiffre_1.setText(String.valueOf(chiffre));
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        // TODO add your handling code here:
        int chiffre = Integer.parseInt(text_chiffre_3.getText());
        
        chiffre--;
        
        if (chiffre<0){
            chiffre=9;
        }
        text_chiffre_3.setText(String.valueOf(chiffre));

    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
        int chiffre = Integer.parseInt(text_chiffre_2.getText());
        
        chiffre++;
        
        if (chiffre > 9) {
        chiffre = 0;
    }
        
         text_chiffre_2.setText(String.valueOf(chiffre));
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
        int chiffre = Integer.parseInt(text_chiffre_3.getText());
        
        chiffre++;
        
        if (chiffre > 9) {
        chiffre = 0;
    }
        
         text_chiffre_3.setText(String.valueOf(chiffre));
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
        int chiffre = Integer.parseInt(text_chiffre_0.getText());
        
        chiffre--;
        
        if (chiffre<0){
            chiffre=9;
        }
        text_chiffre_0.setText(String.valueOf(chiffre));
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
        int chiffre = Integer.parseInt(text_chiffre_1.getText());
        
        chiffre--;
        
        if (chiffre<0){
            chiffre=9;
        }
        text_chiffre_1.setText(String.valueOf(chiffre));
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        // TODO add your handling code here:
        int chiffre = Integer.parseInt(text_chiffre_2.getText());
        
        chiffre--;
        
        if (chiffre<0){
            chiffre=9;
        }
        text_chiffre_2.setText(String.valueOf(chiffre));
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void Bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_testerActionPerformed
        // TODO add your handling code here:
        int[] combinaisonJoueur = new int[4];
    combinaisonJoueur[0] = Integer.parseInt(text_chiffre_0.getText());
    combinaisonJoueur[1] = Integer.parseInt(text_chiffre_1.getText());
    combinaisonJoueur[2] = Integer.parseInt(text_chiffre_2.getText());
    combinaisonJoueur[3] = Integer.parseInt(text_chiffre_3.getText());

    if (combinaisonSecrete.estCorrecte(combinaisonJoueur)) {
        JOptionPane.showMessageDialog(this, "✔️ Code correct !");
    } else {
        JOptionPane.showMessageDialog(this, "❌ Code incorrect !");
    }
        
    }//GEN-LAST:event_Bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> new Cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_tester;
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel text_chiffre_0;
    private javax.swing.JLabel text_chiffre_1;
    private javax.swing.JLabel text_chiffre_2;
    private javax.swing.JLabel text_chiffre_3;
    private javax.swing.JLabel text_consigne;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
